apiVersion: apps/v1
kind: Deployment
metadata:
  name:  myapp
  namespace: myapp-nana
  labels:
    app:  myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      labels:
        app:  myapp
    spec:
      containers:
      - name:  myapp
        image: nanajanashia/argocd-app:1.0 
        ports:
        - containerPort: 8080
          name:  myapp