apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: myapp-nana
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
  - name: MYAPP
    protocol: TCP
    port: 8080
    targetPort: 8080